# Generated by Django 5.0.2 on 2025-01-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('current_score', models.IntegerField(default=0)),
                ('wickets_fallen', models.IntegerField(default=0)),
                ('overs_completed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Over',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_number', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overs', to='match.match')),
            ],
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_number', models.PositiveIntegerField()),
                ('runs', models.IntegerField()),
                ('is_wicket', models.BooleanField(default=False)),
                ('extras', models.IntegerField(default=0)),
                ('over', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='match.over')),
            ],
        ),
    ]
